version: '2'

networks:
    net:
      external: true
      driver: bridge

services:
    chrome:
        image: selenium/standalone-chrome:latest
        hostname: chrome
        networks:
          - net
        ports:
          - 4444:4444
    bot:
        image: ${BOT_IMAGE}
        container_name: bot-main
        networks:
          - net
        depends_on: 
          - chrome
        env_file: 
          - .env
        restart: "no"
        volumes:
          - infodata:/var/info
        deploy:
          resources:
            limits:
              cpus: '0.5'
              memory: 0.5g
          
volumes:
  infodata:
    driver: azure_file
    driver_opts: 
      share_name: tweet-drivers
      storage_account_name: infovolume

